version: 2.1

orbs:
  node: circleci/node@5

jobs:
  stellate-push:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout

      - node/install:
          pkg-manager: pnpm
          install-command: pnpm install --frozen-lockfile

      - run:
          name: Push schema (prod)
          command: pnpm --filter @gcdn/gcdn-push-demo run push
      - run:
          name: Push schema (staging)
          command: pnpm --filter @gcdn/gcdn-push-demo run push -- --env staging

workflows:
  version: 2

  nightly_push:
    triggers:
      - schedule:
          cron: '40 5 * * *' # 05:40 UTC daily
          filters:
            branches:
              only:
                - main
    jobs:
      - stellate-push:
          context:
            - stellate

  config_push:
    jobs:
      - stellate-push:
          context:
            - stellate
          filters:
            branches:
              only:
                - main
