version: 2.1

jobs: 
  stellate: 
    docker: 
      - image: cimg/node:lts
    resource_class: small
    steps: 
      - checkout 
      - run: npx stellate version
      - run: npx stellate push 
      - run: npx stellate push schema
      - run: npx stellate push --env staging

workflows:
  version: 2.1
  nightly_push:
    triggers:
      - schedule:
          # Run this action everyday at 5.40am UTC
          cron: '40 5 * * *'
          filters:
            branches:
              only:
                - main
                - circleci
    jobs:
      - stellate:
          context:
            - stellate
  
  config_push:
    jobs:
      - stellate:
          context:
            - stellate
