name: pull request

on: pull_request

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install the pnpm CLI (auto-detects v9.15.0 from packageManager)
      - name: Install pnpm CLI
        uses: pnpm/action-setup@v4

      # 3) Set up Node.js v18 with pnpm cache
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # 4) Install all workspace dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5) Check formatting (uses the prettier from root devDependencies)
      - name: Check formatting
        run: pnpm exec prettier --check '**/*.{js,jsx,ts,tsx,json,md,mdx}'
