name: pull request

on: pull_request

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (with pnpm cache)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Enable Corepack & activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.2.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm run prettier -- --check '**/*.{js,jsx,ts,tsx,json,md,mdx}'
