name: pull request

on: pull_request

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Cache pnpm store & node_modules
        uses: actions/cache@v2
        with:
          # pnpm keeps a global store plus per-workspace node_modules
          path: |
            ~/.pnpm-store
            **/node_modules
          key: v1-pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm run prettier -- --check '**/*.{js,jsx,ts,tsx,json,md,mdx}'
