name: Stellate
on:
  push:
    branches: [master, github]
    paths:
      - 'gcdn-push-demo/**'
  pull_request:
    branches: [master, github]
    paths:
      - 'gcdn-push-demo/**'

  # Run this action everyday at 5.30am UTC
  schedule:
    - cron: '30 5 * * *'

  # Allow us to manually trigger this workflow
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          check-latest: true
          cache: 'npm'
      - name: Stellate Version
        run: npx stellate version
        env:
          STELLATE_TOKEN: ${{ secrets.STELLATE_TOKEN }}
      - name: Push to Stellate
        run: npx stellate push
        env:
          STELLATE_TOKEN: ${{ secrets.STELLATE_TOKEN }}
      - name: Push Schema Only to Stellate
        run: npx stellate push schema
        env:
          STELLATE_TOKEN: ${{ secrets.STELLATE_TOKEN }}
      - name: Push Environment to Stellate
        run: npx stellate push --env staging
        env:
          STELLATE_TOKEN: ${{ secrets.STELLATE_TOKEN }}
